# Configuration Settings for mosaic, rover

debug: 3

device: tcp://192.168.3.1:28784

serial:
  baudrate: 115200
  mosaic_serial_port: USB1

frame_id: gnss

datum: ETRS89

marker_to_arp:
  delta_e: 0.0
  delta_n: 0.0
  delta_u: 0.0
  
ant_type: Unknown
ant_serial_nr: Unknown

leap_seconds: 18

polling_period:
  pvt: 1
  rest: 1

reconnect_delay_s: 2

use_GNSS_time: true

ntrip_settings:
  mode: Client
  caster: ntrip.flepos.be
  port: 2102
  username: septentrio-demo01
  password: flepos4demo
  mountpoint: FLEPOSDGPSNRS23
  version: v2
  send_gga: auto

publish:
  gpgga: true
  pvtcartesian: true
  pvtgeodetic: true
  poscovgeodetic: true
  atteuler: true
  attcoveuler: true
  navsatfix: true
  gpsfix: true

