# Configuration Settings for mosaic, rover

debug: 3

device: tcp://192.168.3.1:28784

frame_id: gnss

publish:
  gpgga: true
  pvtcartesian: true
  pvtgeodetic: true
  poscovgeodetic: true
  navsatfix: true

serial:
  baudrate: 115200

reconnect_delay_s: 0.1

use_GNSS_time: true
